name: Lint
run-name: Lint
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install code
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          environment-name: lint
          condarc: |
            show_channel_urls: true
            channel_priority: strict
            channels:
              - conda-forge
          create-args: >-
            ruff
      - name: Run Lint
        run: conda info