name: Lint

on:
  workflow_call:
    inputs:
      packages:
        description: 'Packages to install in the environment'
        type: string
        required: ${{ inputs.conda_install_tool == 'micromamba' }}
      lint_command:
        description: 'Command to run linting'
        required: true
        type: string
      conda_install_tool:
        description: 'Tool to use for conda installation (e.g., micromamba)'
        required: false
        type: string
        default: micromamba
      conda_build_tool:
        description: 'Tool to use for conda builds'
        required: false
        type: string

defaults:
  run:
    shell: bash -e -l {0}

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install code with micromamba
        if: ${{ inputs.conda_install_tool == 'micromamba' }}
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          environment-name: lint
          condarc: |
            show_channel_urls: true
            channel_priority: strict
            channels:
              - conda-forge
          create-args: >-
            ${{ inputs.packages }}
      - name: Install code with pixi
        if: ${{ inputs.conda_install_tool == 'pixi' }}
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.45.0
          cache: true
      - name: Run Lint
        run: ${{ inputs.lint_command }}