name: Lint
run-name: Lint
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install code
        uses: mamba-org/setup-micromamba@06375d89d211a1232ef63355742e9e2e564bc7f7
        with:
          environment-name: lint
          condarc: |
            show_channel_urls: true
            channel_priority: strict
            channels:
              - conda-forge
          create-args: >-
            conda-smithy
            pygithub
            requests
            pixi
      - name: Run Lint
        run: conda info