name: Run Lint Workflow with Pixi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with pixi - ${{ github.event.head_commit.message }}
    uses: ./.github/workflows/lint.yaml
    with:
      lint_command: "pixi run lint"
      conda_install_tool: pixi