name: Run Lint Workflow with micromamba

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    name: Lint with micromamba - ${{ github.event.head_commit.message }}
    with:
      conda_install_tool: micromamba
      packages: "ruff pylint"
      lint_command: "ruff check ."