name: Run Lint Workflow with Pixi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    with:
      lint_command: "pixi run lint"
      conda_install_tool: pixi